image: maven:3-jdk-11

stages:
  - build
  - test

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  SONAR_TOKEN: fb911861a0ff4db3bc1b0eaf1a079d2104dae04c
  SONAR_HOST_URL: http://84.237.50.237:9000
  GIT_DEPTH: 0
  
cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean compile
    
test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test
    
sonareqube-check:
  script:
    - mvn sonar:sonar -Dsonar.projectKey=ru.nsu.wallpaper_search:wallpaper_search -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN -Dsonar.core.codeCoveragePlugin=jacoco -Dsonar.jacoco.reportPath=/target/jacoco.exec -Dsonar.dynamicAnalysis=reuseReports -Dsonar.surefire.reportsPath=/target/test-reports
  allow_failure: true
  only:
    - master
