image: maven:3-jdk-13

stages:
  - build
  - test
  - production

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean compile
    
test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test
    
production:
  stage: production
  script:
    - mvn $MAVEN_CLI_OPTS production